### ISSUE TITLE
Request for Assistane

### ISSUE THREAD

**Issue by Chidinma6** [daGiardini/GeoGuard-App#1]
Hi daGiardini
I am a final year student. This project is very similar to my final year project and I really need your help
Firstly, I need to a detailed and clear circuit diagram of your project and also a real life picture of it
Secondly, I need a guide on the software aspect as android studio no longer uses java but kotlin

Thank you so much

**Comment by daGiardini** [comment]
Hi @Chidinma6,
Thank you for reaching out. I'm currently working on preparing the detailed and clear circuit diagram for you, along with a scheme to explain how the Android app works. You can expect to receive these details in the next few days.

**Comment by Chidinma6** [comment]
Thank you so much @daGiardini 
I am quite sorry to say that I need the diagram like tomorrow, I am so behind schedule.
I have checked YouTube but they don't have something like yours.
And please can you highlight the part were I need to connect the hardware (esp32) to the andriod app. I am using an esp32 because it is cheaper than buying an arduino board and then a wifi module.

**Comment by daGiardini** [comment]
@Chidinma6 The communication is through the MQTT protocol. The ESP32 publishes data to a specific topic on a Mosquitto server, and the mobile device subscribes to that topic to receive the data.

**Comment by Chidinma6** [comment]
@daGiardini I will read more about that.
And I think I should download the older version of Android studio for the app

**Comment by daGiardini** [comment]
![tracker](https://github.com/daGiardini/GeoGuard-App/assets/79969976/735692ee-614e-4da2-bf04-02868fe90b44)
@Chidinma6 On the left, there's the ESP32, on the right, at the top, is the SIM module, and at the bottom, the GPS module. Finally, below the battery. I'll send the connection diagram later today.

**Comment by Chidinma6** [comment]
Thank you soooo mucchhhh
sorry i can't really see the battery and what type of battery did you use. I guess a 3.7v battery
should there be a wire or not

**Comment by daGiardini** [comment]
@Chidinma6 I don't have it on hand at the moment, so I'm unable to send a photo of the bottom part. The device is powered by a 3.7V LiPo battery, which is charged using a micro USB Type-B charging module. Additionally, there's a switch for powering the device on and off.

**Comment by Chidinma6** [comment]
@daGiardini  Please when it is on hand, kindly send a photo.
Hmmmm... the switch is interesting. Will it be included in the circuit diagram?

**Comment by daGiardini** [comment]
@Chidinma6 **Important note**: remeber to add your own API key for Google Maps Android API in the AndroidManifest.xml file.
[Here](https://developers.google.com/maps/documentation/android-sdk/start#create-project)

**Comment by Chidinma6** [comment]
@daGiardini what is your advice to someone who is new to this project.
I have never worked with arduino and andriod app projects before

**Comment by daGiardini** [comment]
@Chidinma6 
![IMG_68914](https://github.com/daGiardini/GeoGuard-App/assets/79969976/d10cdf95-f725-418d-837d-439cc6803e6b)
Battery
![IMG_6898 (1)](https://github.com/daGiardini/GeoGuard-App/assets/79969976/ede9a12d-946f-4306-973a-0ba817fa2633)

**Comment by daGiardini** [comment]
![circuit](https://github.com/daGiardini/GeoGuard-App/assets/79969976/0806aaea-ad2c-451d-8b75-8a4e855195dd)
Circuit diagram

**Comment by Chidinma6** [comment]
@daGiardini  what is your advice to someone who is new to this project.
I have never worked with arduino and andriod app projects before
And also please what is the use of the switch and USB port

**Comment by daGiardini** [comment]
@Chidinma6 **For Android**, I would advise focusing primarily on understanding the various types of services and how they function, as well as the usage of broadcast receivers. These components are fundamental for many Android applications and will provide a solid foundation for the project. Additionally, familiarize yourself with Android intents, which are a fundamental part of Android's inter-component communication mechanism. Intents are used to trigger actions or request services from other components, such as starting activities, services, or sending broadcasts.

- [Services](https://developer.android.com/develop/background-work/services)
- [Broadcast Receiver](https://developer.android.com/develop/background-work/background-tasks/broadcasts#context-registered-receivers)
- [Intent](https://developer.android.com/reference/android/content/Intent)

As **for Arduino**, if you have a good foundation in C/C++, you'll find Arduino code quite straightforward. I would suggest starting by exploring the documentation of the libraries I used in the project. Understanding how these libraries work and how to use them effectively will be essential for working with the ESP32 microcontroller.

The **USB port**, a micro USB Type B, is used for recharging the LiPo battery. It serves as the charging input for the battery
The **switch** is used for turning on and off the ESP32 and other components. This allows for manual control of the device's power supply, conserving power or shutting down the device when not in use.

Additionally, it's important to understand how the **MQTT protocol** works. MQTT is the communication protocol used in this project, allowing devices to publish and subscribe to topics for data exchange. Understanding the principles of MQTT, such as topics, publishers, subscribers, and brokers, will be essential for effective communication between the ESP32 and the mobile app.

**Comment by daGiardini** [comment]
- The **USB port**, a micro USB Type B, is used for recharging the LiPo battery. It serves as the charging input for the battery
- The **switch** is used for turning on and off the ESP32 and other components. This allows for manual control of the device's power supply, conserving power or shutting down the device when not in use.

**Comment by Chidinma6** [comment]
Hi what type of wires do I need for soldering and connection

**Comment by daGiardini** [comment]
@Chidinma6 For soldering and making connections, you'll typically need insulated solid-core wires. These wires are commonly used in electronics projects and are available in various gauges and colors. Solid-core wires are easier to work with for soldering purposes compared to stranded wires

**Comment by daGiardini** [comment]
@Chidinma6 Could I close this "issue"?

**Comment by Chidinma6** [comment]
@daGiardini Please, can we close it next Monday?
And please, did you use resistors during connection and soldering?

**Comment by Chidinma6** [comment]
@daGiardini  I am unable to install ESP32 board platform
I am getting this error 
Some indexes could not be updated. Get "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json": read tcp 192.168.206.167:50400->185.199.110.133:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

**Comment by daGiardini** [comment]
@Chidinma6 No resistors used. The error message suggests a timeout or failure to establish a connection with the server. Given that it's a server-related problem, unfortunately, there isn't much you can do to resolve it.

**Comment by Chidinma6** [comment]
@daGiardini  I have been on this since Thursday, and it hasn't been done yet. The installation is still having errors
Did this happen to you?

**Comment by daGiardini** [comment]
@Chidinma6 I've tried with the same URL but I'm not experiencing any issues on my end.

**Comment by Chidinma6** [comment]
@daGiardini there is network issue over her at my country. I think that maybe the cause
